### ISSUE TITLE
Expose "Process.wait2" as an option in DaemonRunner::ShellOut

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/daemon_runner#18]
We'd like to expose [Process.wait2](http://ruby-doc.org/core-2.3.1/Process.html#method-c-wait2) as an feature in `DaemonRunner::ShellOut`. I'm thinking the interface will look something like this

```ruby
wait2(pid = nil, flags = 0)
```

If `pid` is `nil`, the pid from a process started with a `wait: false` argument is used. The method returns a [Process::Status](http://ruby-doc.org/core-2.3.1/Process/Status.html) object or `nil` if a process with a matching pid was not found.

**Comment by athompson-r7** [comment]
> The method returns a Process::Status object or nil if a process with a matching pid was not found.

You are saying this new method should? Or `Process.wait2` does?  AFAIK `Process.wait2` returns and `Array` of `[pid, status]`.

**Comment by athompson-r7** [comment]
@fmitchell-r7 I think this proposal is perfect.  We can rescue `Errno::ECHILD` to handle the case where the process isn't running pretty cleanly.

**Comment by fmitchell-r7** [comment]
> You are saying this new method should? Or Process.wait2 does? AFAIK Process.wait2 returns and Array of [pid, status].

@athompson-r7, this new method should only return the `Process::Status`.
